#!/usr/bin/python

import fcntl
import os
import sys
import time

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print "USAGE: %s [lockfile] [command]" % sys.argv[0]
        exit(1)

    fd = open(sys.argv[1], 'w')
    while True:
        try:
            fcntl.lockf(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except IOError:
            time.sleep(0.5)
        else:
            break

    cmd = " ".join(sys.argv[2:])
    ret = os.system(cmd)
    fcntl.lockf(fd, fcntl.LOCK_UN)
    fd.close()
    exit(ret)

